// Generated by scripts/build-resources.mjs from resources/**/*.md. Do not edit.
import type { ResourceDocument } from "@portents/core";

export const resources: readonly ResourceDocument[] = [
	{
		"schemaVersion": 1,
		"id": "portents/greywater/faction/river-cult",
		"settingId": "portents/greywater",
		"kind": "faction",
		"name": "Keepers of the Due",
		"aliases": [
			"river cult",
			"the Keepers"
		],
		"tags": [
			"river",
			"shrine",
			"debt"
		],
		"links": [
			"portents/greywater/place/riverside-shrine",
			"portents/greywater/npc/nesta",
			"portents/greywater/thread/river-debt"
		],
		"audience": [
			"gm"
		],
		"body": "The Keepers maintain ferries, clear flood debris, and conduct public rites at the first spring rise. Most members understand the work as civic duty wrapped in old ceremony.\n\nThe inner circle knows the river bargains are literal. They disagree over whether the accumulated unpaid obligations should be discharged carefully or invoked all at once against Greywater's council.\n"
	},
	{
		"schemaVersion": 1,
		"id": "portents/greywater/npc/nesta",
		"settingId": "portents/greywater",
		"kind": "npc",
		"name": "Nesta Vey",
		"aliases": [
			"Nesta",
			"shrine keeper"
		],
		"tags": [
			"river-cult",
			"keeper"
		],
		"links": [
			"portents/greywater/place/riverside-shrine",
			"portents/greywater/faction/river-cult",
			"portents/greywater/thread/river-debt"
		],
		"audience": [
			"gm"
		],
		"body": "Nesta is the shrine's practical, unsentimental keeper. She trusts work performed in bad weather more than promises made indoors.\n\nShe knows the current cult copied its river tokens from older examples without understanding that each token records a particular obligation. She will not volunteer this while she believes the questioner wants power over the ward rather than a way to settle the debt.\n"
	},
	{
		"schemaVersion": 1,
		"id": "portents/greywater/place/flooded-causeway",
		"settingId": "portents/greywater",
		"kind": "place",
		"name": "Flooded Causeway",
		"aliases": [
			"the causeway",
			"marsh road"
		],
		"tags": [
			"road",
			"marsh",
			"flood"
		],
		"links": [
			"portents/greywater/place/greywater-city",
			"portents/greywater/place/ruined-watchtower"
		],
		"audience": [
			"all"
		],
		"body": "The raised road crosses three miles of reed beds north of Greywater. At ordinary water it is slow but safe. After sustained rain, the central mile disappears beneath brown water and travelers follow old stone posts by touch.\n\nLocals leave a strip of blue cloth on the last dry post when the crossing becomes dangerous.\n"
	},
	{
		"schemaVersion": 1,
		"id": "portents/greywater/place/greywater-city",
		"settingId": "portents/greywater",
		"kind": "place",
		"name": "Greywater",
		"aliases": [
			"Greywater City",
			"the river city"
		],
		"tags": [
			"city",
			"river",
			"trade"
		],
		"links": [
			"portents/greywater/place/riverside-shrine",
			"portents/greywater/place/flooded-causeway",
			"portents/greywater/faction/river-cult"
		],
		"audience": [
			"all"
		],
		"body": "Greywater stands where the old north road meets a broad, slow river. Its stone quay and crowded timber upper town depend on barges, ferries, and the uncertain patience of the surrounding marsh.\n\nThe city council speaks as if it governs the river. Boat crews, shrine keepers, and anyone who has watched the water rise know better.\n"
	},
	{
		"schemaVersion": 1,
		"id": "portents/greywater/place/riverside-shrine",
		"settingId": "portents/greywater",
		"kind": "place",
		"name": "Old Riverside Shrine",
		"aliases": [
			"riverside shrine",
			"old shrine"
		],
		"tags": [
			"river",
			"shrine",
			"ward"
		],
		"links": [
			"portents/greywater/place/greywater-city",
			"portents/greywater/npc/nesta",
			"portents/greywater/faction/river-cult",
			"portents/greywater/thread/river-debt"
		],
		"audience": [
			"gm"
		],
		"body": "The roofless shrine sits downstream from Greywater on the south bank. Silver channels cut into its altar carry rain toward the river even when the stone is level.\n\nThe shrine is older than the present river cult. Its ward recognizes obligations rather than worship: a true token records a debt accepted and eventually paid. A false token wakes the ward without satisfying it.\n"
	},
	{
		"schemaVersion": 1,
		"id": "portents/greywater/place/ruined-watchtower",
		"settingId": "portents/greywater",
		"kind": "place",
		"name": "North Watchtower",
		"aliases": [
			"ruined watchtower",
			"north tower"
		],
		"tags": [
			"ruin",
			"hills",
			"road"
		],
		"links": [
			"portents/greywater/place/flooded-causeway",
			"portents/greywater/thread/river-debt"
		],
		"audience": [
			"gm"
		],
		"body": "Only the lower storey remains intact. From its broken stair, a watcher can see the north road, the flooded flats, and smoke rising from Greywater.\n\nA rain-tight chamber below the tower contains old toll records. Several entries describe payments made to the river itself, decades after the official toll was abolished.\n"
	},
	{
		"schemaVersion": 1,
		"id": "portents/greywater/thread/river-debt",
		"settingId": "portents/greywater",
		"kind": "thread",
		"name": "The River's Due",
		"aliases": [
			"river debt",
			"the due"
		],
		"tags": [
			"mystery",
			"debt",
			"flood"
		],
		"links": [
			"portents/greywater/place/riverside-shrine",
			"portents/greywater/place/ruined-watchtower",
			"portents/greywater/npc/nesta",
			"portents/greywater/faction/river-cult"
		],
		"audience": [
			"gm"
		],
		"body": "Greywater has accepted the river's protection for generations while allowing the duties attached to it to become ceremony, then folklore, then inconvenience.\n\nThe debt is not a demand for treasure or sacrifice. It consists of neglected acts: maintaining old channels, sheltering travelers during floods, and leaving part of the southern marsh unclaimed. The ward reacts to forged tokens because forgery attempts to claim protection without accepting any duty.\n"
	}
];
