// Generated by scripts/build-guidance.mjs from ../guidance/*.md. Do not edit.
//
// The markdown is the source. Run `pnpm build:guidance` after changing it, or
// `pnpm build:guidance --check` to see whether this file is stale.

import type { SystemGuidance } from "@portent/core";

export const guidance: readonly SystemGuidance[] = [
	{
		id: "dnd-5e-2014",
		aliases: ["5e (2014)","5e 2014","dnd 5e 2014","d&d 5e 2014"],
		body: "# D&D 5E — 2014 printing\n\nThis is the printing in play. State it in one clause when you confirm the setup, and do not drift to the other one.\n\n## What is specific to this printing\n\n- The original 2014 Player's Handbook. Race grants ability modifiers, backgrounds do\n  not. Surprise costs the whole first turn. No weapon mastery.\n- If the player says a bare \"5e\" they most likely mean the 2024 rules; this printing was\n  chosen deliberately, so do not drift back toward it.\n\n## In combat\n\n- Action, bonus action, movement, one free object interaction, reaction.\n- Advantage/disadvantage: `2d20kh1` and `2d20kl1`. Use these liberally as your main\n  dial instead of inventing situational modifiers.\n- Death saves: three failures dies, three successes stabilises, a natural 20 is back up\n  at 1 HP. These are the player's own rolls, never the GM's. Record the running count\n  in the sheet's `Death Saves` status key after each one.\n- Concentration: when the player takes damage while concentrating, ask for a CON save\n  at DC 10 or half the damage, whichever is higher. Track what they are concentrating on\n  in the sheet's Status block so you remember to ask.\n- Crits: double the dice, not the modifier. Optionally draw `crit-hits` instead.",
	},
	{
		id: "dnd-5e-2024",
		aliases: ["5e","dnd","d&d","dnd 5e","d&d 5e","5e (2024)","5e 2024","dnd 5e 2024","d&d 5e 2024"],
		body: "# D&D 5E — 2024 printing\n\nThis is the printing in play. State it in one clause when you confirm the setup, and do not drift to the other one.\n\n## What is specific to this printing\n\n- Weapon mastery properties, new backgrounds granting ability bonuses, species instead\n  of race with no ability modifiers, revised exhaustion, unarmed strikes as grapple/shove\n  options, and reworked class features at most levels.\n- Surprise is a Perception-vs-Stealth initiative penalty rather than a lost turn.\n\n## In combat\n\n- Action, bonus action, movement, one free object interaction, reaction.\n- Advantage/disadvantage: `2d20kh1` and `2d20kl1`. Use these liberally as your main\n  dial instead of inventing situational modifiers.\n- Death saves: three failures dies, three successes stabilises, a natural 20 is back up\n  at 1 HP. These are the player's own rolls, never the GM's. Record the running count\n  in the sheet's `Death Saves` status key after each one.\n- Concentration: when the player takes damage while concentrating, ask for a CON save\n  at DC 10 or half the damage, whichever is higher. Track what they are concentrating on\n  in the sheet's Status block so you remember to ask.\n- Crits: double the dice, not the modifier. Optionally draw `crit-hits` instead.",
	},
];
