// Generated by scripts/build-guidance.mjs from ../guidance/*.md. Do not edit.
//
// The markdown is the source. Run `pnpm build:guidance` after changing it, or
// `pnpm build:guidance --check` to see whether this file is stale.

import type { SystemGuidance } from "@portent/core";

export const guidance: readonly SystemGuidance[] = [
	{
		id: "generic",
		aliases: ["generic","generic d20","d20"],
		body: "# Generic d20 fantasy\n\nNo printed rules to be faithful to, which makes rulings your own to make.\n\n- Pick a target number, say it out loud, and be consistent about it afterwards.\n- d20 plus a modifier against a DC. 10 easy, 15 moderate, 20 hard.\n- Say when something is a ruling rather than a rule, and write recurring rulings into\n  `campaign.md` so the next session matches this one.\n- Do not silently import 5E or Pathfinder specifics. If you need one, say you are\n  borrowing it.",
	},
];
