// Generated by scripts/build-guidance.mjs from ../guidance/*.md. Do not edit.
//
// The markdown is the source. Run `pnpm build:guidance` after changing it, or
// `pnpm build:guidance --check` to see whether this file is stale.

import type { SystemGuidance } from "@portents/core";

export const guidance: readonly SystemGuidance[] = [
	{
		id: "generic",
		aliases: ["generic","generic d20","d20"],
		body: "# Generic d20 fantasy\n\nNo printed rules to be faithful to, which makes rulings your own to make.\n\n- Pick a target number, say it out loud, and be consistent about it afterwards.\n- d20 plus a modifier against a DC. 10 easy, 15 moderate, 20 hard.\n- Say when something is a ruling rather than a rule, and write recurring rulings into\n  `campaign.md` so the next session matches this one.\n- Do not silently import 5E or Pathfinder specifics. If you need one, say you are\n  borrowing it.\n\n## Sidekicks\n\nWith no printed rules to be faithful to, keep a sidekick to a card rather than a sheet:\na name, what it is good at, what it is afraid of, a rough hit-point pool, and one thing\nit can do that the main character cannot.\n\nResolve its actions with the same target numbers you use for anyone else, one step\nworse when it is acting outside what it is good at. Do not track its resources in\ndetail; a sidekick's job is to make fights survivable and scenes less lonely, not to\nadd bookkeeping.",
	},
];
