/**
 * @portent/core — a solo tabletop RPG engine.
 *
 * Deterministic generators an agent or an application drives: dice, map tiles,
 * and (as they land) decks, random tables and oracles. Nothing here calls a
 * language model, and nothing here touches a filesystem except through the
 * Storage port, so the same code runs in Node and in a browser.
 *
 * ```ts
 * import { roll, formatRoll, parseTile, renderAscii, renderSvg } from "@portent/core";
 * import { dungeonTiles } from "@portent/content-generic";
 *
 * formatRoll(roll("6#4d6kh3"));   // ability scores
 * renderSvg(parseTile(mySource)); // the same tile the ASCII shows
 * ```
 *
 * Content lives in `@portent/content`, not here. This package knows how to
 * parse, validate and render tiles; it ships none of them.
 */

// Ports: the capabilities the library needs from its host.
export {
	assertValidKey,
	type Clock,
	cryptoRandomSource,
	defaultRandomSource,
	fixedClock,
	InvalidKeyError,
	isValidKey,
	type RandomSource,
	randomSeed,
	randomSourceFrom,
	seededRandomSource,
	type Storage,
	StorageError,
	type StorageKey,
	StorageUnavailableError,
	systemClock,
	tickingClock,
} from "./ports/index.ts";

// Dice.
export {
	analyze,
	chanceOf,
	type Condition,
	diceSummary,
	type Distribution,
	type Expr,
	type FnName,
	formatDistribution,
	formatRoll,
	MAX_REPEATS,
	type Modifier,
	type ModifierType,
	parse,
	type ParsedExpression,
	percentileOf,
	type RepeatedExpression,
	roll,
	type RolledGroup,
	rollExpression,
	type RollOptions,
	type RollResult,
	splitRepeat,
} from "./dice/index.ts";

// Map tiles.
export {
	assertStandardTile,
	CELL_SPECS,
	type CellKind,
	type CellSpec,
	census,
	type ComposedMap,
	composeTiles,
	type ComposeOptions,
	connectorPositions,
	connects,
	edgeCentre,
	type Edge,
	edgesOf,
	type Exit,
	exitsOf,
	glyphOf,
	isPassable,
	isStandardTile,
	kindsIn,
	knownGlyphs,
	legendFor,
	legendOf,
	MAX_TILE_SIZE,
	mergeCells,
	parchmentTheme,
	parseTile,
	parseTileSet,
	readSvgCells,
	readSvgSymbols,
	readSvgTokens,
	renderAscii,
	renderSvg,
	slateTheme,
	specOf,
	specOfGlyph,
	STANDARD_TILE_SIZE,
	standardEdges,
	type StandardTileOptions,
	standardTileProblems,
	type SvgOptions,
	symbolId,
	type Theme,
	type Tile,
	tileAt,
	TileParseError,
	type TileSource,
	type TokenLike,
	toTileSource,
	type Viewport,
	type VisibilityMask,
} from "./tiles/index.ts";

// Tile transforms: one authored bend covers all four orientations.
export {
	mirrorTile,
	type QuarterTurns,
	rotatePoint,
	rotateTile,
	rotations,
	withRotations,
} from "./tiles/transform.ts";

// Maps: generation, field of view, and what the party knows.
export {
	type Actor,
	actorAt,
	actorGlyph,
	type ActorKind,
	actorSees,
	addActor,
	type AsciiViewOptions,
	type CellSet,
	cellFromKey,
	cellKey,
	type CellState,
	cellState,
	computeFov,
	createView,
	type CreateViewOptions,
	describeSignature,
	forgetAll,
	type FovOptions,
	type GeneratedDungeon,
	generateDungeon,
	type GenerateOptions,
	GenerationError,
	hasLineOfSight,
	indexBySignature,
	isVisible,
	type MapView,
	missingSignatures,
	moveActor,
	type Position,
	reachableCells,
	recomputeVisibility,
	removeActor,
	renderAsciiView,
	revealAll,
	revealArea,
	revealTile,
	tileSignature,
	visibleActors,
	withActors,
} from "./map/index.ts";

// Content packs: the model content is written against.
export {
	type ContentPack,
	type ContentRegistry,
	createRegistry,
	DuplicateContentError,
	emptyRegistry,
	type Provenance,
	type RegistryOptions,
	ATTRIBUTION_REQUIRED,
	type Attribution,
	type AttributedItem,
	CONTENT_LICENSES,
	type ContentLicense,
	isContentLicense,
	packageLicenseFor,
	provenanceProblems,
	renderAttribution,
	renderNotice,
	requiresAttribution,
	type AppliedOverride,
	type ContentKind,
	type ContentOverride,
	UnknownContentError,
	UnusedOverrideError,
} from "./packs/index.ts";

// Decks, with piles the caller owns and persists.
export {
	type Card,
	createPile,
	type Deck,
	DeckError,
	deckProblems,
	deckSize,
	drawEphemeral,
	drawFromPile,
	type DrawnCard,
	type DrawOptions,
	type DrawResult,
	expandDeck,
	formatCard,
	peekPile,
	type Pile,
	pileMatchesDeck,
	type PileOptions,
	pileStatus,
	type PileStatus,
	recentlyDrawn,
	returnToTop,
} from "./decks/index.ts";

// Random tables, with recursive composition.
export {
	formatTableResult,
	rollTable,
	rollTableById,
	type RollTableOptions,
	type Table,
	TableError,
	type TableEntry,
	tableProblems,
	tableReferences,
	type TableResult,
} from "./tables/index.ts";

// The oracle: mechanism here, words in a content pack.
export {
	formatYesNo,
	oracleAnswer,
	ORACLE_KINDS,
	type OracleKind,
	type OracleRequest,
	type OracleResponse,
	gmMove,
	howMany,
	type Likelihood,
	LIKELIHOODS,
	meaning,
	missingOracleTables,
	ORACLE_TABLES,
	type OracleDetail,
	type OracleOptions,
	reaction,
	sceneCheck,
	yesNo,
	type YesNoAnswer,
	type YesNoResult,
} from "./oracle/index.ts";

// Character sheets: markdown files that are both machine- and human-readable.
export {
	appendToSection,
	applyDelta,
	createSheet,
	type CreateSheetInput,
	emitFrontmatter,
	type Frontmatter,
	FrontmatterError,
	type FrontmatterValue,
	GENERATED_SECTIONS,
	type GeneratedKey,
	getSection,
	hasFrontmatter,
	isConsistent,
	isGeneratedSection,
	listSections,
	type MarkdownDocument,
	parseDocument,
	parseSheet,
	patchMap,
	patchStatus,
	renderGeneratedSection,
	type Scalar,
	setMeta,
	setSection,
	type Sheet,
	SheetError,
	sheetProblems,
	status,
	statusDigest,
	statusValue,
	stringifyDocument,
	stringifySheet,
	syncGeneratedSections,
} from "./sheets/index.ts";
export {
	genericSheet,
	matchSheet,
	normaliseSystem,
	type SheetTemplate,
	type TemplateSection,
	templateProblems,
} from "./sheets/template.ts";

// The roll ledger: an append-only record that makes solo play auditable.
export {
	type AppendInput,
	describeVerifyResult,
	EVENT_KINDS,
	type EventKind,
	formatId,
	isEventKind,
	isSecretKind,
	kindLabel,
	Ledger,
	type LedgerEntry,
	LedgerError,
	type LedgerOptions,
	ledgerProblems,
	nextSequence,
	type ParsedId,
	parseId,
	parseLedger,
	SECRET_KINDS,
	sequenceOf,
	serialiseEntry,
	type VerifyResult,
	verifyId,
} from "./ledger/index.ts";

// Markdown section manipulation, shared by sheets and campaign notes.
export {
	appendToSectionBody,
	hasSection,
	lastSections,
	removeSection,
	type Section,
	sectionBody,
	sectionHeadings,
	sections,
	setSectionBody,
} from "./markdown/index.ts";

// A campaign on disk: state in frontmatter, everything readable as markdown.
export {
	CAMPAIGN_ROOT,
	Campaign,
	type CampaignClock,
	type CampaignDeps,
	CampaignError,
	campaignKeys,
	type CampaignSummary,
	type CreateCampaignInput,
	defaultEdition,
	describeRules,
	type Edition,
	editionNote,
	editionsFor,
	formatSystem,
	isEditionOf,
	KNOWN_SYSTEMS,
	knownSystem,
	type ParsedSystem,
	parseSystem,
	type PendingRoll,
	resolveEdition,
	resolveSystemLine,
	type RulesSystem,
	type Scene,
	slugify,
	SystemError,
	systemLabel,
	WORLD_SECTIONS,
	type WorldSection,
} from "./campaign/index.ts";
