/**
 * Hold the port against fixtures captured from the live prototype.
 *
 * Parity is claimed only for what a player reads and an LLM is prompted with:
 * dice parsing, roll formatting, and the tool contract. Sheets, campaign files
 * and ledger ids changed deliberately, and PARITY.md lists why.
 *
 * The fixture is regenerated by `node scripts/capture-parity.mjs` against the
 * prototype. A failure here means one of two things, and the test messages say
 * which to check: either the port diverged, or the prototype was changed after
 * the fixture was taken.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { formatRoll, parse, randomSourceFrom, roll, splitRepeat } from "@portent/core";
import type { RandomSource } from "@portent/core";

interface RollFixture {
	expression: string;
	cycle: number;
	total?: number;
	formatted?: string;
	groups?: Array<{ die: string; rolls: number[]; kept: number[] }>;
	hasMax?: boolean;
	hasMin?: boolean;
	threw?: string;
}

interface Fixtures {
	capturedFrom: string;
	/** Read from the fixture, never redeclared here: two lists would drift. */
	faceCycles: number[][];
	rolls: RollFixture[];
	repeats: Array<{ input: string; times?: number; expression?: string; threw?: string }>;
	parseErrors: Array<{ input: string; message?: string; accepted?: boolean }>;
}

const here = dirname(fileURLToPath(import.meta.url));
const fixtures: Fixtures = JSON.parse(readFileSync(join(here, "../fixtures/dice-parity.json"), "utf8"));

const FACE_CYCLES = fixtures.faceCycles;

/**
 * A `RandomSource` that yields the fixture's faces.
 *
 * Both implementations must draw randomness in the same order for a comparison
 * to mean anything, so this pins consumption order too: a port that rolls the
 * same dice in a different sequence gives different results from one seed, and
 * nothing else would notice.
 */
function scriptedSource(faces: number[]): RandomSource {
	let i = 0;
	const next = () => faces[i++ % faces.length];
	// Built from the real helper so pick/shuffle/weighted exist, then int is
	// overridden to match the prototype's scripted rng exactly. Deriving int from
	// float would map the fixture's faces differently and the comparison would
	// silently stop meaning anything.
	return {
		...randomSourceFrom(() => (next() % 100) / 100),
		int: (min: number, max: number) => {
			const value = next();
			const span = max - min + 1;
			return min + (((value - min) % span) + span) % span;
		},
	};
}

describe("dice parity with the prototype", () => {
	it("has fixtures to compare against", () => {
		assert.ok(fixtures.rolls.length > 100, `only ${fixtures.rolls.length} fixtures; re-run capture-parity.mjs`);
		assert.ok(Array.isArray(FACE_CYCLES) && FACE_CYCLES.length > 0, "the fixture carries no face cycles");
		assert.equal(
			FACE_CYCLES.length,
			new Set(fixtures.rolls.map((entry) => entry.cycle)).size,
			"a face cycle produced no fixtures",
		);
		// At least one cycle must have strictly distinct values, or keep-highest and
		// keep-lowest are indistinguishable and those fixtures prove nothing.
		assert.ok(
			FACE_CYCLES.some((cycle) => cycle.length > 3 && new Set(cycle).size === cycle.length),
			"no cycle can tell keep-highest from keep-lowest",
		);
	});

	for (const fixture of fixtures.rolls) {
		const label = `${fixture.expression} (cycle ${fixture.cycle})`;
		it(`matches ${label}`, () => {
			const rng = scriptedSource(FACE_CYCLES[fixture.cycle]);
			if (fixture.threw !== undefined) {
				assert.throws(
					() => roll(fixture.expression, { rng }),
					`prototype rejected ${label} with ${JSON.stringify(fixture.threw)}, port accepted it`,
				);
				return;
			}
			const result = roll(fixture.expression, { rng });
			assert.equal(result.total, fixture.total, `total differs for ${label}`);
			assert.equal(
				formatRoll(result),
				fixture.formatted,
				`the line the player reads differs for ${label}`,
			);
			assert.deepEqual(
				result.groups.map((group) => ({
					die: `${group.die.count}d${group.die.sides}`,
					rolls: group.rolls,
					kept: group.kept,
				})),
				fixture.groups,
				`dice consumption order or keep-logic differs for ${label}`,
			);
			assert.equal(result.hasMax ?? false, fixture.hasMax, `hasMax differs for ${label}`);
			assert.equal(result.hasMin ?? false, fixture.hasMin, `hasMin differs for ${label}`);
		});
	}
});

describe("repeat syntax parity", () => {
	for (const fixture of fixtures.repeats) {
		it(`splits ${fixture.input}`, () => {
			if (fixture.threw !== undefined) {
				assert.throws(() => splitRepeat(fixture.input));
				return;
			}
			const { times, expression } = splitRepeat(fixture.input);
			assert.equal(times, fixture.times);
			assert.equal(expression, fixture.expression);
		});
	}
});

describe("rejection parity", () => {
	// The message is what the player sees when they typo an expression, so it is
	// part of the contract rather than an implementation detail.
	for (const fixture of fixtures.parseErrors) {
		it(`rejects ${JSON.stringify(fixture.input)}`, () => {
			if (fixture.accepted) {
				assert.doesNotThrow(() => parse(fixture.input), `prototype accepted ${JSON.stringify(fixture.input)}`);
				return;
			}
			assert.throws(
				() => parse(fixture.input),
				`prototype rejected ${JSON.stringify(fixture.input)} but the port accepted it`,
			);
		});
	}
});
