export {
	assertResource,
	assertSetting,
	COMMON_RESOURCE_KINDS,
	isNamespacedId,
	isResourceSegment,
	MAX_RESOURCE_CHARACTERS,
	RESOURCE_SCHEMA_VERSION,
	resourceAudience,
	type ResourceAudience,
	ResourceContractError,
	type ResourceDocument,
	type ResourceRecord,
	resourceProblems,
	type SettingManifest,
	settingProblems,
} from "./resource.ts";
export {
	assertSettingImageMap,
	SETTING_IMAGE_MIME_TYPES,
	type SettingImageMap,
	type SettingImageMimeType,
	type SettingMapAsset,
	type SettingMapPin,
	settingImageMapProblems,
} from "./image-map.ts";
