export {
	assertResource,
	assertSetting,
	type CampaignResourceRecord,
	COMMON_RESOURCE_KINDS,
	formatResourceList,
	formatResourceRecord,
	isNamespacedId,
	isResourceSegment,
	MAX_RESOURCE_CHARACTERS,
	parseResourceDocument,
	queryResourceRecords,
	RESOURCE_SCHEMA_VERSION,
	resourceAudience,
	type ResourceAudience,
	ResourceContractError,
	type ResourceDocument,
	type ResourceQuery,
	type ResourceRecord,
	resourceProblems,
	type PackResourceRecord,
	resourceVisibleTo,
	type SettingManifest,
	settingProblems,
	stringifyResourceDocument,
} from "./resource.ts";
export {
	assertSettingImageMap,
	formatSettingImageMap,
	SETTING_IMAGE_MIME_TYPES,
	type SettingImageMap,
	type SettingImageMapRecord,
	type SettingImageMimeType,
	type SettingMapAsset,
	type SettingMapPin,
	settingImageMapProblems,
} from "./image-map.ts";
